version: '3.1'

services:
  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
      - ./kafka-init.sh:/docker-entrypoint-init.d/kafka-init.sh
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - TrackingNetwork

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - TrackingNetwork

  consumer:
    build:
      context: ./consumer
    restart: always
    depends_on:
      - kafka
      - postgres
      - producer1
      - producer2
    networks:
      - TrackingNetwork

  producer1:
    build:
      context: ./producer
    restart: always
    depends_on:
      - kafka
    networks:
      - TrackingNetwork
    environment:
      - NODE_ENV=ip1
    command: npm start

  producer2:
    build:
      context: ./producer
    restart: always
    depends_on:
      - kafka
    networks:
      - TrackingNetwork
    environment:
      - NODE_ENV=ip2
    command: npm start
      
  api:
    build:
      context: ./api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres
    networks:
      - TrackingNetwork

  frontend:
    build:
      context: ./front
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - TrackingNetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - TrackingNetwork


networks:
  TrackingNetwork:


volumes:
  kafka_data: